### ISSUE TITLE
Can't open Yuzu on linux

### ISSUE THREAD

**Issue by quinton-ashley** [yuzu-emu/yuzu-canary#7]
Can't open Yuzu on linux:

error while loading shared libraries: libQt5WebEngineWidgets.so.5: cannot open shared object file: No such file or directory

This is where the relevant file is on my computer but yuzu can't seem to find it:
```
$ sudo find / -name libQt5WebEngineWidgets.so.5
/home/qashto/.local/share/flatpak/runtime/org.kde.Platform/x86_64/5.11/02ede84d3591a5ea8028204d86059bffaccb778159ec53c859bbc60d9e7025e8/files/lib/libQt5WebEngineWidgets.so.5
```

**Comment by ChrisSlS** [comment]
Hi,

You know, it's usually enough to make a request on google. In two clicks, the problem is repaired:
 
`sudo apt install qtwebengine5-dev`

**Comment by quinton-ashley** [comment]
sorry to bother you but I did install that and it still doesn't work

**Comment by ChrisSlS** [comment]
I was not careful, but it looks like you're using KDE. So there may be other packages to install.

This is what the [asterisk](https://linux.die.net/man/8/apt-get) does:

> Finally, the apt_preferences(5) mechanism allows you to create an
alternative installation policy for individual packages.
If no package matches the given expression and the expression contains one
of ".", "?" or "*" then it is assumed to be a POSIX regular expression, and it is applied to all package names in the database. Any matches are then installed (or removed). Note that matching is done by substring so "lo.*" matches "how-lo" and "lowest". If this is undesired, anchor the regular expression with a "^" or "$" character, or create a more specific regular expression.

After installing the latest packages, what error do you encounter ?

**Comment by quinton-ashley** [comment]
I don't encounter any error after installing with the asterisks.  Thanks :)
